---
- name: "Play 1 : Demo Vserver creation, FlexVol creation and FlexVol deletion" 
  hosts: localhost
  connection: local
  
  vars: 
   netapp_hostname: 172.16.130.41
   netapp_username: admin
   netapp_password: netapp123

  tasks:   
  - name: Create Vserver "nithya_vserver" in "aggr_n2_data"
    na_cdot_svm:
      state: present
      name: nithya_vserver
      root_volume: nithya_vserver_root
      root_volume_aggregate: aggr_n2_data
      root_volume_security_style: unix
      hostname: "{{ netapp_hostname }}"
      username: "{{ netapp_username }}"
      password: "{{ netapp_password }}"
  
  - name: Create volume "nithya_vol01" in Vserver "nithya_vserver"
    na_cdot_volume: 
      state: present
      name: nithya_vol01
      infinite: False
      aggregate_name: aggr_n2_data
      size: 20
      size_unit: mb
      vserver: nithya_vserver
      hostname: "{{ netapp_hostname }}"
      username: "{{ netapp_username }}"
      password: "{{ netapp_password }}"

  - name: Create volume "nithya_vol02" in Vserver "nithya_vserver"
    na_cdot_volume: 
      state: present
      name: nithya_vol02
      infinite: False
      aggregate_name: aggr_n2_data
      size: 20
      size_unit: mb
      vserver: nithya_vserver
      hostname: "{{ netapp_hostname }}"
      username: "{{ netapp_username }}"
      password: "{{ netapp_password }}"

  #- name: Offline volume "nithya_vol01" in Vserver "nithya_vserver"
  #  na_cdot_volume: 
  #    state: present
  #    name: nithya_vol01
  #    infinite: False
  #    aggregate_name: aggr_n2_data
  #    is_online: false
  #    size: 20
  #    size_unit: mb 
  #    vserver: nithya_vserver
  #    hostname: "{{ netapp_hostname }}"
  #    username: "{{ netapp_username }}"
  #    password: "{{ netapp_password }}"
  #
  #- name: Delete volume "nithya_vol01" in Vserver "nithya_vserver"FlexVol
  #  na_cdot_volume: 
  #    state: absent
  #    name: nithya_vol01
  #    infinite: False
  #    aggregate_name: aggr_n2_data
  #    online: false 
  #    vserver: nithya_vserver
  #    hostname: "{{ netapp_hostname }}"
  #    username: "{{ netapp_username }}"
  #    password: "{{ netapp_password }}"
